### ISSUE TITLE
How to set orientation to VERTICAL?

### ISSUE THREAD

**Issue by AbhinayMe** [sparrow007/CarouselRecyclerview#7]
I liked your library. Thank you.

Do this support for vertical scroll?

**Comment by sparrow007** [comment]
I am really glad that you like the library,

Do you want a stack card kind of layout?

**Comment by AbhinayMe** [comment]
Something like this.

![ic0OT](https://user-images.githubusercontent.com/6308616/121837164-8bde5100-cd07-11eb-9cd5-2c019dc14dfb.png)

**Comment by AbhinayMe** [comment]
Hi, Any update on this?

**Comment by sparrow007** [comment]
@AbhinayMe actually this would be a different layout manager, you know it's stack layout, but if you guys wanted to have the same layout manager in this library, I'll start working on it now.

**Comment by AbhinayMe** [comment]
That's great to hear. Thanks for support.

**Comment by reco1I** [comment]
Any update about this?
